# Generated by Django 5.1 on 2024-10-03 07:56

import VideosSave.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideosSave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[VideosSave.models.validate_video_file]),
        ),
    ]
