# Generated by Django 5.1 on 2024-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideosSave', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
