# Generated by Django 5.1 on 2024-10-03 10:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideosSave', '0003_video_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cloudinary_url',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
