# Generated by Django 5.1 on 2024-10-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideosSave', '0004_remove_video_cloudinary_url_video_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
