# Generated by Django 5.1 on 2024-10-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideosSave', '0006_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
